name: OWASP ZAP Integration with GitHub Actions

on: [push]

permissions:
  contents: read
  issues: write
  security-events: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
          target: "http://testphp.vulnweb.com/"
          rules_file_name: ".zap/rules.tsv"
          cmd_options: "-a"
          issue_title: false
          fail_action: true
